<Project>
  <Import Project="$(MSBuildThisFileDirectory)TrayAppDotNET.Parent.props" />

  <PropertyGroup>
    <Platforms Condition="'$(Platforms)' == ''">x64</Platforms>
    <PlatformTarget Condition="'$(PlatformTarget)' == ''">x64</PlatformTarget>
    <Platform Condition="'$(Platform)' == ''">x64</Platform>
  </PropertyGroup>
</Project>
