using System.Text;

namespace TrayAppDotNETCommon.AxamlPropertyLinker;

internal static class AXAMLProvenanceEmitter
{
    public const string HintName = "AxamlPropertyLinker.AxamlProvenance.g.cs";

    public static string Generate(
        IReadOnlyList<AXAMLProvenanceDocument> documents,
        string generatedNamespace)
    {
        List<AXAMLProvenanceDocument> orderedDocuments = [];
        HashSet<string> documentKeys = new(StringComparer.OrdinalIgnoreCase);
        foreach (AXAMLProvenanceDocument document in documents
                     .OrderBy(static document => document.SourcePath, StringComparer.OrdinalIgnoreCase)
                     .ThenBy(static document => document.OwnerTypeName, StringComparer.Ordinal))
        {
            string documentKey = document.SourcePath + "\0" + document.OwnerTypeName;
            if (documentKeys.Add(documentKey)) orderedDocuments.Add(document);
        }

        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#if DEBUG");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ");
        builder.AppendLine(generatedNamespace);
        builder.AppendLine("{");
        builder.AppendLine("    internal static class AXAMLProvenanceCatalog");
        builder.AppendLine("    {");
        builder.AppendLine("        private static readonly global::TrayAppDotNETCommon.UI.Debugging.AXAMLProvenanceEntry[] EntriesStorage =");
        builder.AppendLine("        [");

        foreach (AXAMLProvenanceDocument document in orderedDocuments)
        {
            foreach (AXAMLProvenanceItem entry in document.Entries)
                AppendEntry(builder, document, entry);
        }

        builder.AppendLine("        ];");
        builder.AppendLine();
        builder.AppendLine("        internal static global::System.Collections.Generic.IReadOnlyList<global::TrayAppDotNETCommon.UI.Debugging.AXAMLProvenanceEntry> Entries =>");
        builder.AppendLine("            EntriesStorage;");
        builder.AppendLine();
        builder.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("        internal static void Register() =>");
        builder.AppendLine("            global::TrayAppDotNETCommon.UI.Debugging.DebugUIProvenance.RegisterAXAML(");
        builder.AppendLine("                typeof(AXAMLProvenanceCatalog).Assembly,");
        builder.AppendLine("                EntriesStorage);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine("#endif");
        return builder.ToString();
    }

    private static void AppendEntry(
        StringBuilder builder,
        AXAMLProvenanceDocument document,
        AXAMLProvenanceItem entry)
    {
        builder.AppendLine("            new global::TrayAppDotNETCommon.UI.Debugging.AXAMLProvenanceEntry(");
        builder.Append("                global::TrayAppDotNETCommon.UI.Debugging.AXAMLProvenanceKind.");
        builder.AppendLine(entry.Kind.ToString() + ",");
        AppendArgument(builder, document.SourcePath);
        builder.Append("                ");
        builder.Append(entry.Line);
        builder.AppendLine(",");
        builder.Append("                ");
        builder.Append(entry.Column);
        builder.AppendLine(",");
        AppendArgument(builder, document.OwnerTypeName);
        AppendArgument(builder, entry.ElementTypeName);
        AppendArgument(builder, entry.ElementPath);
        AppendArgument(builder, entry.ControlName);
        AppendArgument(builder, entry.PropertyName);
        AppendArgument(builder, entry.ResourceKey);
        AppendArgument(builder, entry.ValueExpression);
        AppendLastArgument(builder, entry.Selector);
        builder.AppendLine("            ),");
    }

    private static void AppendArgument(StringBuilder builder, string? value)
    {
        builder.Append("                ");
        builder.Append(value == null ? "null" : StringLiteral(value));
        builder.AppendLine(",");
    }

    private static void AppendLastArgument(StringBuilder builder, string? value)
    {
        builder.Append("                ");
        builder.AppendLine(value == null ? "null" : StringLiteral(value));
    }

    private static string StringLiteral(string value)
    {
        StringBuilder builder = new();
        builder.Append('"');
        foreach (char character in value)
        {
            switch (character)
            {
                case '\\':
                    builder.Append(@"\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\r':
                    builder.Append(@"\r");
                    break;
                case '\n':
                    builder.Append(@"\n");
                    break;
                case '\t':
                    builder.Append(@"\t");
                    break;
                default:
                    builder.Append(character);
                    break;
            }
        }

        builder.Append('"');
        return builder.ToString();
    }
}
