using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace TrayAppDotNETCommon.AxamlPropertyLinker;

internal static class CSharpBuilderProvenanceEmitter
{
    public const string HintName = "AxamlPropertyLinker.CSharpBuilderProvenance.g.cs";

    public static string Generate(
        ImmutableArray<CSharpBuilderBoundary> boundaries,
        string rootNamespace)
    {
        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#if DEBUG");
        builder.Append("namespace ").Append(rootNamespace).AppendLine(".GeneratedDebugging");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class CSharpBuilderProvenanceCatalog");
        builder.AppendLine("    {");
        builder.AppendLine("        private static readonly global::TrayAppDotNETCommon.UI.Debugging.CSharpBuilderProvenanceEntry[] Entries =");
        builder.AppendLine("        [");

        foreach (CSharpBuilderBoundary boundary in boundaries
                     .OrderBy(static value => value.SourcePath, StringComparer.OrdinalIgnoreCase)
                     .ThenBy(static value => value.BoundaryLine))
        {
            foreach (CSharpBuilderAssignment assignment in boundary.Assignments)
            {
                builder.AppendLine("            new(");
                builder.Append("                ").Append(Literal(boundary.SourcePath)).AppendLine(",");
                builder.Append("                ").Append(boundary.BoundaryLine).AppendLine(",");
                builder.Append("                ").Append(assignment.PropertyReference).AppendLine(",");
                builder.Append("                global::TrayAppDotNETCommon.UI.Debugging.DebugPropertyAssignmentOperation.")
                    .Append(assignment.Operation).AppendLine(",");
                builder.Append("                ").Append(Literal(assignment.ValueExpression)).AppendLine(",");
                builder.Append("                ").Append(assignment.SourceLine).AppendLine(",");
                builder.Append("                ").Append(assignment.SourceColumn).AppendLine(",");
                builder.Append("                ").Append(Literal(assignment.SourceMember)).AppendLine(",");
                builder.Append("                ").Append(assignment.ResourceKey == null
                    ? "null"
                    : Literal(assignment.ResourceKey)).AppendLine("),");
            }
        }

        builder.AppendLine("        ];");
        builder.AppendLine();
        builder.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("        internal static void Register() =>");
        builder.AppendLine("            global::TrayAppDotNETCommon.UI.Debugging.DebugUIProvenance.RegisterCSharpBuilders(Entries);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine("#endif");
        return builder.ToString();
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
}
