//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace FanControlTrayAppDotNET.Localization {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Strings {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("FanControlTrayAppDotNET.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to argb hex:.
        /// </summary>
        public static string ColorPicker_ArgbHexLabel {
            get {
                return ResourceManager.GetString("ColorPicker_ArgbHexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alpha.
        /// </summary>
        public static string ColorPicker_ChannelLabel_Alpha {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        public static string ColorPicker_ChannelLabel_B {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string ColorPicker_ChannelLabel_G {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hue.
        /// </summary>
        public static string ColorPicker_ChannelLabel_Hue {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r.
        /// </summary>
        public static string ColorPicker_ChannelLabel_R {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ColorPicker_CloseTooltip {
            get {
                return ResourceManager.GetString("ColorPicker_CloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ColorPicker_DefaultButton {
            get {
                return ResourceManager.GetString("ColorPicker_DefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPicker.
        /// </summary>
        public static string ColorPicker_DefaultTitle {
            get {
                return ResourceManager.GetString("ColorPicker_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ColorPicker_ResetButton {
            get {
                return ResourceManager.GetString("ColorPicker_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rgba hex:.
        /// </summary>
        public static string ColorPicker_RgbaHexLabel {
            get {
                return ResourceManager.GetString("ColorPicker_RgbaHexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Flyout_DeleteGroup_Confirm {
            get {
                return ResourceManager.GetString("Flyout_DeleteGroup_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}? Fans in this group will be moved out of the group..
        /// </summary>
        public static string Flyout_DeleteGroup_MessageFormat {
            get {
                return ResourceManager.GetString("Flyout_DeleteGroup_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete group.
        /// </summary>
        public static string Flyout_DeleteGroup_Title {
            get {
                return ResourceManager.GetString("Flyout_DeleteGroup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for fan options.
        /// </summary>
        public static string Flyout_FanButton_Tooltip {
            get {
                return ResourceManager.GetString("Flyout_FanButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle between manual and curve control.
        /// </summary>
        public static string Flyout_ModeLock_Tooltip {
            get {
                return ResourceManager.GetString("Flyout_ModeLock_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redock the flyout to the tray corner..
        /// </summary>
        public static string Flyout_Redock_Tooltip {
            get {
                return ResourceManager.GetString("Flyout_Redock_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undock the flyout. Drag to move it; drop near the tray icon to redock..
        /// </summary>
        public static string Flyout_Undock_Tooltip {
            get {
                return ResourceManager.GetString("Flyout_Undock_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Settings_About_AuthorLabel {
            get {
                return ResourceManager.GetString("Settings_About_AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Settings_About_BuildLabel {
            get {
                return ResourceManager.GetString("Settings_About_BuildLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string Settings_About_CheckForUpdates_Button {
            get {
                return ResourceManager.GetString("Settings_About_CheckForUpdates_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodically ask GitHub if a newer release is available..
        /// </summary>
        public static string Settings_About_CheckForUpdates_Description {
            get {
                return ResourceManager.GetString("Settings_About_CheckForUpdates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates automatically.
        /// </summary>
        public static string Settings_About_CheckForUpdates_Title {
            get {
                return ResourceManager.GetString("Settings_About_CheckForUpdates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string Settings_About_GithubLabel {
            get {
                return ResourceManager.GetString("Settings_About_GithubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install update.
        /// </summary>
        public static string Settings_About_InstallUpdate_Available {
            get {
                return ResourceManager.GetString("Settings_About_InstallUpdate_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version stale.
        /// </summary>
        public static string Settings_About_InstallUpdate_Stale {
            get {
                return ResourceManager.GetString("Settings_About_InstallUpdate_Stale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        public static string Settings_About_InstallUpdate_UpToDate {
            get {
                return ResourceManager.GetString("Settings_About_InstallUpdate_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}d ago.
        /// </summary>
        public static string Settings_About_RelativeTime_DaysFormat {
            get {
                return ResourceManager.GetString("Settings_About_RelativeTime_DaysFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h ago.
        /// </summary>
        public static string Settings_About_RelativeTime_HoursFormat {
            get {
                return ResourceManager.GetString("Settings_About_RelativeTime_HoursFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string Settings_About_RelativeTime_JustNow {
            get {
                return ResourceManager.GetString("Settings_About_RelativeTime_JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}m ago.
        /// </summary>
        public static string Settings_About_RelativeTime_MinutesFormat {
            get {
                return ResourceManager.GetString("Settings_About_RelativeTime_MinutesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        public static string Settings_About_RuntimeLabel {
            get {
                return ResourceManager.GetString("Settings_About_RuntimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_About_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_About_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float an Update! button in the top-right of the flyout while a new version is available..
        /// </summary>
        public static string Settings_About_ShowUpdateButton_Description {
            get {
                return ResourceManager.GetString("Settings_About_ShowUpdateButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show update button in flyout.
        /// </summary>
        public static string Settings_About_ShowUpdateButton_Title {
            get {
                return ResourceManager.GetString("Settings_About_ShowUpdateButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise a tray notification when a new version is detected..
        /// </summary>
        public static string Settings_About_ShowUpdateNotifications_Description {
            get {
                return ResourceManager.GetString("Settings_About_ShowUpdateNotifications_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification for updates.
        /// </summary>
        public static string Settings_About_ShowUpdateNotifications_Title {
            get {
                return ResourceManager.GetString("Settings_About_ShowUpdateNotifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A WPF tray app skeleton..
        /// </summary>
        public static string Settings_About_Tagline {
            get {
                return ResourceManager.GetString("Settings_About_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update actions.
        /// </summary>
        public static string Settings_About_UpdateActions_Title {
            get {
                return ResourceManager.GetString("Settings_About_UpdateActions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often the background update check runs. The timer resets every time you click Check for updates..
        /// </summary>
        public static string Settings_About_UpdateInterval_Description {
            get {
                return ResourceManager.GetString("Settings_About_UpdateInterval_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  min.
        /// </summary>
        public static string Settings_About_UpdateInterval_MinutesSuffix {
            get {
                return ResourceManager.GetString("Settings_About_UpdateInterval_MinutesSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check interval.
        /// </summary>
        public static string Settings_About_UpdateInterval_Title {
            get {
                return ResourceManager.GetString("Settings_About_UpdateInterval_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Settings_About_Updates_Header {
            get {
                return ResourceManager.GetString("Settings_About_Updates_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available: {0}.
        /// </summary>
        public static string Settings_About_UpdateStatus_AvailableFormat {
            get {
                return ResourceManager.GetString("Settings_About_UpdateStatus_AvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string Settings_About_UpdateStatus_Checking {
            get {
                return ResourceManager.GetString("Settings_About_UpdateStatus_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re up to date. Last checked {0}..
        /// </summary>
        public static string Settings_About_UpdateStatus_LastCheckedFormat {
            get {
                return ResourceManager.GetString("Settings_About_UpdateStatus_LastCheckedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update check has run yet..
        /// </summary>
        public static string Settings_About_UpdateStatus_NeverChecked {
            get {
                return ResourceManager.GetString("Settings_About_UpdateStatus_NeverChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update service is not available..
        /// </summary>
        public static string Settings_About_UpdateStatus_Unavailable {
            get {
                return ResourceManager.GetString("Settings_About_UpdateStatus_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_Common_Page_About {
            get {
                return ResourceManager.GetString("Settings_Common_Page_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Properties.
        /// </summary>
        public static string Settings_Common_Page_FanProperties {
            get {
                return ResourceManager.GetString("Settings_Common_Page_FanProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout.
        /// </summary>
        public static string Settings_Common_Page_Flyout {
            get {
                return ResourceManager.GetString("Settings_Common_Page_Flyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_Common_Page_General {
            get {
                return ResourceManager.GetString("Settings_Common_Page_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string Settings_Common_Page_Hotkeys {
            get {
                return ResourceManager.GetString("Settings_Common_Page_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Common_Page_Theme {
            get {
                return ResourceManager.GetString("Settings_Common_Page_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon.
        /// </summary>
        public static string Settings_Common_Page_TrayIcon {
            get {
                return ResourceManager.GetString("Settings_Common_Page_TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Settings_FanProperties_Apply_Button {
            get {
                return ResourceManager.GetString("Settings_FanProperties_Apply_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve assigned to newly discovered fans. Select None to leave new fans in hardware control..
        /// </summary>
        public static string Settings_FanProperties_DefaultAssignedCurve_Description {
            get {
                return ResourceManager.GetString("Settings_FanProperties_DefaultAssignedCurve_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Assigned Curve.
        /// </summary>
        public static string Settings_FanProperties_DefaultAssignedCurve_Title {
            get {
                return ResourceManager.GetString("Settings_FanProperties_DefaultAssignedCurve_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed change in fan speed per second, expressed in duty cycle %. Caps how aggressively curves ramp fans up or down..
        /// </summary>
        public static string Settings_FanProperties_DefaultDeltaMaxDutyCycle_Description {
            get {
                return ResourceManager.GetString("Settings_FanProperties_DefaultDeltaMaxDutyCycle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Delta Max Duty Cycle.
        /// </summary>
        public static string Settings_FanProperties_DefaultDeltaMaxDutyCycle_Title {
            get {
                return ResourceManager.GetString("Settings_FanProperties_DefaultDeltaMaxDutyCycle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial duty cycle applied for one tick to overcome fan stiction. Always in duty cycle %; skipped when a fan&apos;s startup speed is already higher..
        /// </summary>
        public static string Settings_FanProperties_DefaultJumpstartDutyCycle_Description {
            get {
                return ResourceManager.GetString("Settings_FanProperties_DefaultJumpstartDutyCycle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Jumpstart Duty Cycle.
        /// </summary>
        public static string Settings_FanProperties_DefaultJumpstartDutyCycle_Title {
            get {
                return ResourceManager.GetString("Settings_FanProperties_DefaultJumpstartDutyCycle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag or Ctrl+Up/Down to reorder.
        /// </summary>
        public static string Settings_FanProperties_FanSettingsCard_Tooltip {
            get {
                return ResourceManager.GetString("Settings_FanProperties_FanSettingsCard_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No live fans detected..
        /// </summary>
        public static string Settings_FanProperties_NoFans {
            get {
                return ResourceManager.GetString("Settings_FanProperties_NoFans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat this fan as non-functioning. {0}.
        /// </summary>
        public static string Settings_FanProperties_NonFunctioning_DescriptionFormat {
            get {
                return ResourceManager.GetString("Settings_FanProperties_NonFunctioning_DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually tag fans as non-functioning.
        /// </summary>
        public static string Settings_FanProperties_NonFunctioning_Header {
            get {
                return ResourceManager.GetString("Settings_FanProperties_NonFunctioning_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag setting cards onto fixed fan slots, then Apply to swap per-fan settings..
        /// </summary>
        public static string Settings_FanProperties_Reassign_Description {
            get {
                return ResourceManager.GetString("Settings_FanProperties_Reassign_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan reassignment.
        /// </summary>
        public static string Settings_FanProperties_Reassign_Header {
            get {
                return ResourceManager.GetString("Settings_FanProperties_Reassign_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign fan settings.
        /// </summary>
        public static string Settings_FanProperties_Reassign_Title {
            get {
                return ResourceManager.GetString("Settings_FanProperties_Reassign_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Properties.
        /// </summary>
        public static string Settings_FanProperties_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_FanProperties_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen the flyout in its previously-undocked window if it was undocked when the app last closed..
        /// </summary>
        public static string Settings_Flyout_RestoreUndockState_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_RestoreUndockState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore undocked flyout on startup.
        /// </summary>
        public static string Settings_Flyout_RestoreUndockState_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_RestoreUndockState_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout.
        /// </summary>
        public static string Settings_Flyout_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_Flyout_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the undock button in the flyout header. Disabling hides the button and forces the flyout back into its docked position..
        /// </summary>
        public static string Settings_Flyout_ShowUndockButton_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_ShowUndockButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow flyout to be undocked.
        /// </summary>
        public static string Settings_Flyout_ShowUndockButton_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_ShowUndockButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Settings_General_Apply_Button {
            get {
                return ResourceManager.GetString("Settings_General_Apply_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically save changes..
        /// </summary>
        public static string Settings_General_Autosave_Description {
            get {
                return ResourceManager.GetString("Settings_General_Autosave_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-save.
        /// </summary>
        public static string Settings_General_Autosave_Title {
            get {
                return ResourceManager.GetString("Settings_General_Autosave_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Settings_General_Cancel_Button {
            get {
                return ResourceManager.GetString("Settings_General_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently running from &quot;{0}&quot;..
        /// </summary>
        public static string Settings_General_CurrentlyRunning_Format {
            get {
                return ResourceManager.GetString("Settings_General_CurrentlyRunning_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newly discovered fans will report speeds in RPM rather than duty cycle %. Existing fans keep their per-fan setting..
        /// </summary>
        public static string Settings_General_DefaultToRPMMode_Description {
            get {
                return ResourceManager.GetString("Settings_General_DefaultToRPMMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default to RPM Mode.
        /// </summary>
        public static string Settings_General_DefaultToRPMMode_Title {
            get {
                return ResourceManager.GetString("Settings_General_DefaultToRPMMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Settings_General_Install_Button {
            get {
                return ResourceManager.GetString("Settings_General_Install_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Settings_General_Installation_Header {
            get {
                return ResourceManager.GetString("Settings_General_Installation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will copy the running exe to &quot;{0}&quot; and register it in Windows Settings &gt; Apps..
        /// </summary>
        public static string Settings_General_InstallConfirm_Message_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstallConfirm_Message_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install FanControlTrayAppDotNET?.
        /// </summary>
        public static string Settings_General_InstallConfirm_Title {
            get {
                return ResourceManager.GetString("Settings_General_InstallConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed at &quot;{0}&quot;..
        /// </summary>
        public static string Settings_General_Installed_Format {
            get {
                return ResourceManager.GetString("Settings_General_Installed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed (older build) at &quot;{0}&quot;.{1}.
        /// </summary>
        public static string Settings_General_InstalledOlderBuild_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstalledOlderBuild_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed build {0}, running build {1}. Click Update to overwrite.{2}.
        /// </summary>
        public static string Settings_General_InstalledOutOfDate_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstalledOutOfDate_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed (build {0}) at &quot;{1}&quot;..
        /// </summary>
        public static string Settings_General_InstalledWithBuild_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstalledWithBuild_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install failed.
        /// </summary>
        public static string Settings_General_InstallFailed_Title {
            get {
                return ResourceManager.GetString("Settings_General_InstallFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will copy the running exe to &quot;{0}&quot; and register it in Windows Settings &gt; Apps. Requires admin..
        /// </summary>
        public static string Settings_General_InstallSystemWideConfirm_Message_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstallSystemWideConfirm_Message_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install FanControlTrayAppDotNET system-wide?.
        /// </summary>
        public static string Settings_General_InstallSystemWideConfirm_Title {
            get {
                return ResourceManager.GetString("Settings_General_InstallSystemWideConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local user.
        /// </summary>
        public static string Settings_General_LocalUser_Title {
            get {
                return ResourceManager.GetString("Settings_General_LocalUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not installed. Will be placed at &quot;{0}&quot;.{1}.
        /// </summary>
        public static string Settings_General_NotInstalled_Format {
            get {
                return ResourceManager.GetString("Settings_General_NotInstalled_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (requires admin).
        /// </summary>
        public static string Settings_General_RequiresAdmin_Suffix {
            get {
                return ResourceManager.GetString("Settings_General_RequiresAdmin_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch FanControlTrayAppDotNET when you sign in to Windows..
        /// </summary>
        public static string Settings_General_RunOnStartup_Description {
            get {
                return ResourceManager.GetString("Settings_General_RunOnStartup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///Target: {1}.
        /// </summary>
        public static string Settings_General_RunOnStartup_OnDescriptionFormat {
            get {
                return ResourceManager.GetString("Settings_General_RunOnStartup_OnDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart shortcut placed in shell:startup..
        /// </summary>
        public static string Settings_General_RunOnStartup_OnHeaderLine {
            get {
                return ResourceManager.GetString("Settings_General_RunOnStartup_OnHeaderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on startup automatically.
        /// </summary>
        public static string Settings_General_RunOnStartup_Title {
            get {
                return ResourceManager.GetString("Settings_General_RunOnStartup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string Settings_General_Seconds_Suffix {
            get {
                return ResourceManager.GetString("Settings_General_Seconds_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_General_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not installed via the Windows Store..
        /// </summary>
        public static string Settings_General_StoreNotInstalled {
            get {
                return ResourceManager.GetString("Settings_General_StoreNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently running from a Windows Store package..
        /// </summary>
        public static string Settings_General_StoreRunning {
            get {
                return ResourceManager.GetString("Settings_General_StoreRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System wide.
        /// </summary>
        public static string Settings_General_SystemWide_Title {
            get {
                return ResourceManager.GetString("Settings_General_SystemWide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Settings_General_Uninstall_Button {
            get {
                return ResourceManager.GetString("Settings_General_Uninstall_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall completed with warnings. Some files or registry entries may need manual removal. Check the install location and Windows Settings &gt; Apps..
        /// </summary>
        public static string Settings_General_UninstallIncomplete_Message {
            get {
                return ResourceManager.GetString("Settings_General_UninstallIncomplete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall incomplete.
        /// </summary>
        public static string Settings_General_UninstallIncomplete_Title {
            get {
                return ResourceManager.GetString("Settings_General_UninstallIncomplete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Settings_General_Update_Button {
            get {
                return ResourceManager.GetString("Settings_General_Update_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Store.
        /// </summary>
        public static string Settings_General_WindowsStore_Title {
            get {
                return ResourceManager.GetString("Settings_General_WindowsStore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Settings_Hotkeys_Add_Button {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete this hotkey.
        /// </summary>
        public static string Settings_Hotkeys_DeleteHotkey_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_DeleteHotkey_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists.
        /// </summary>
        public static string Settings_Hotkeys_Exists_Button {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Exists_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Settings_Hotkeys_Key_Enter {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        public static string Settings_Hotkeys_Key_Escape {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageDown.
        /// </summary>
        public static string Settings_Hotkeys_Key_PageDown {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageUp.
        /// </summary>
        public static string Settings_Hotkeys_Key_PageUp {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string Settings_Hotkeys_Key_Space {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_Alt {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+Shift.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_AltShift {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_AltShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+Shift+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_AltShiftWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_AltShiftWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_AltWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_AltWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_Ctrl {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlAlt {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Shift.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlAltShift {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlAltShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Shift+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlAltShiftWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlAltShiftWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlAltWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlAltWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlShift {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlShiftWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlShiftWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_Shift {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_ShiftWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_ShiftWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_Win {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the fan flyout above the tray icon..
        /// </summary>
        public static string Settings_Hotkeys_OpenFlyout_Description {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_OpenFlyout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open flyout.
        /// </summary>
        public static string Settings_Hotkeys_OpenFlyout_Title {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_OpenFlyout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this settings window..
        /// </summary>
        public static string Settings_Hotkeys_OpenSettings_Description {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_OpenSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string Settings_Hotkeys_OpenSettings_Title {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_OpenSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Settings_Hotkeys_Remove_Button {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Remove_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Settings_Hotkeys_SearchLabel {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind a system-wide keyboard shortcut to each action. Bindings require at least one modifier key (Ctrl, Alt, Shift, or Win). All actions start unbound..
        /// </summary>
        public static string Settings_Hotkeys_SectionDescription {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_SectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts.
        /// </summary>
        public static string Settings_Hotkeys_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey service not available..
        /// </summary>
        public static string Settings_Hotkeys_Status_HotkeyServiceUnavailable {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Status_HotkeyServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered..
        /// </summary>
        public static string Settings_Hotkeys_Status_Registered {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Status_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Theme_Appearance_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_Appearance_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme background color.
        /// </summary>
        public static string Settings_Theme_BackgroundColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundColor_DarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the default background color. Each variant falls back to the default when unset..
        /// </summary>
        public static string Settings_Theme_BackgroundColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme background color.
        /// </summary>
        public static string Settings_Theme_BackgroundColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundColor_LightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string Settings_Theme_BackgroundColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme card border color.
        /// </summary>
        public static string Settings_Theme_CardBorderColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_CardBorderColor_DarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the outline color for fan and group cards. Each variant falls back to the default when unset..
        /// </summary>
        public static string Settings_Theme_CardBorderColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_CardBorderColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme card border color.
        /// </summary>
        public static string Settings_Theme_CardBorderColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_CardBorderColor_LightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card border color.
        /// </summary>
        public static string Settings_Theme_CardBorderColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_CardBorderColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show outlines around fan and group cards..
        /// </summary>
        public static string Settings_Theme_CardBorders_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_CardBorders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card borders.
        /// </summary>
        public static string Settings_Theme_CardBorders_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_CardBorders_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the left and right spacing between root-level cards and the flyout edge..
        /// </summary>
        public static string Settings_Theme_CardHorizontalInset_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_CardHorizontalInset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card side inset.
        /// </summary>
        public static string Settings_Theme_CardHorizontalInset_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_CardHorizontalInset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the vertical spacing between fan cards and group cards..
        /// </summary>
        public static string Settings_Theme_CardSpacing_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_CardSpacing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card spacing.
        /// </summary>
        public static string Settings_Theme_CardSpacing_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_CardSpacing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu.
        /// </summary>
        public static string Settings_Theme_ContextMenu_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_ContextMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme fan card background color.
        /// </summary>
        public static string Settings_Theme_FanCardBackgroundColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_FanCardBackgroundColor_DarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the background color for individual fan cards. Each variant falls back to the default when unset..
        /// </summary>
        public static string Settings_Theme_FanCardBackgroundColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_FanCardBackgroundColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme fan card background color.
        /// </summary>
        public static string Settings_Theme_FanCardBackgroundColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_FanCardBackgroundColor_LightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan card background.
        /// </summary>
        public static string Settings_Theme_FanCardBackgroundColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_FanCardBackgroundColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout.
        /// </summary>
        public static string Settings_Theme_Flyout_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_Flyout_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme flyout background color.
        /// </summary>
        public static string Settings_Theme_FlyoutBackgroundColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutBackgroundColor_DarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the background color behind the fan and group cards. Each variant falls back to the default when unset..
        /// </summary>
        public static string Settings_Theme_FlyoutBackgroundColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutBackgroundColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme flyout background color.
        /// </summary>
        public static string Settings_Theme_FlyoutBackgroundColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutBackgroundColor_LightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout background.
        /// </summary>
        public static string Settings_Theme_FlyoutBackgroundColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutBackgroundColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme flyout title bar background color.
        /// </summary>
        public static string Settings_Theme_FlyoutTitleBarBackgroundColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutTitleBarBackgroundColor_DarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the background color for the flyout title bar. Each variant falls back to the default when unset..
        /// </summary>
        public static string Settings_Theme_FlyoutTitleBarBackgroundColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutTitleBarBackgroundColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme flyout title bar background color.
        /// </summary>
        public static string Settings_Theme_FlyoutTitleBarBackgroundColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutTitleBarBackgroundColor_LightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout title bar background.
        /// </summary>
        public static string Settings_Theme_FlyoutTitleBarBackgroundColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutTitleBarBackgroundColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the spacing between the flyout title bar and the first row of cards..
        /// </summary>
        public static string Settings_Theme_FlyoutTitleBarCardSpacing_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutTitleBarCardSpacing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar card spacing.
        /// </summary>
        public static string Settings_Theme_FlyoutTitleBarCardSpacing_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutTitleBarCardSpacing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the overall size of the tray context menu. All elements scale from font size..
        /// </summary>
        public static string Settings_Theme_FontSize_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_FontSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string Settings_Theme_FontSize_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_FontSize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme group card background color.
        /// </summary>
        public static string Settings_Theme_GroupCardBackgroundColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_GroupCardBackgroundColor_DarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the background color for grouped fan cards. Each variant falls back to the default when unset..
        /// </summary>
        public static string Settings_Theme_GroupCardBackgroundColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_GroupCardBackgroundColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme group card background color.
        /// </summary>
        public static string Settings_Theme_GroupCardBackgroundColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_GroupCardBackgroundColor_LightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group card background.
        /// </summary>
        public static string Settings_Theme_GroupCardBackgroundColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_GroupCardBackgroundColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint fan cards inside groups with the group card background instead of the fan card background..
        /// </summary>
        public static string Settings_Theme_GroupedFanCardBackground_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_GroupedFanCardBackground_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use group background in groups.
        /// </summary>
        public static string Settings_Theme_GroupedFanCardBackground_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_GroupedFanCardBackground_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide individual fan-card outlines when a fan is inside a group..
        /// </summary>
        public static string Settings_Theme_HideGroupedFanCardBorders_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_HideGroupedFanCardBorders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide grouped fan card borders.
        /// </summary>
        public static string Settings_Theme_HideGroupedFanCardBorders_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_HideGroupedFanCardBorders_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When card borders are off, show an outline only on the card under the pointer..
        /// </summary>
        public static string Settings_Theme_HoverCardBorders_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_HoverCardBorders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover card border.
        /// </summary>
        public static string Settings_Theme_HoverCardBorders_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_HoverCardBorders_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dark.
        /// </summary>
        public static string Settings_Theme_PickerTitle_DarkVariant {
            get {
                return ResourceManager.GetString("Settings_Theme_PickerTitle_DarkVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string Settings_Theme_PickerTitle_Format {
            get {
                return ResourceManager.GetString("Settings_Theme_PickerTitle_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light.
        /// </summary>
        public static string Settings_Theme_PickerTitle_LightVariant {
            get {
                return ResourceManager.GetString("Settings_Theme_PickerTitle_LightVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Settings_Theme_Reset {
            get {
                return ResourceManager.GetString("Settings_Theme_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies rounded corners to the flyout, settings cards, buttons, and menus. Turn off for a squared-off look..
        /// </summary>
        public static string Settings_Theme_RoundedCorners_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_RoundedCorners_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounded corners.
        /// </summary>
        public static string Settings_Theme_RoundedCorners_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_RoundedCorners_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_Theme_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the flyout title bar square even when rounded corners are enabled..
        /// </summary>
        public static string Settings_Theme_SquareFlyoutTitleBarCorners_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_SquareFlyoutTitleBarCorners_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square title bar corners.
        /// </summary>
        public static string Settings_Theme_SquareFlyoutTitleBarCorners_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_SquareFlyoutTitleBarCorners_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme tray icon color.
        /// </summary>
        public static string Settings_Theme_StaticIconColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_StaticIconColor_DarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the default tray icon color. Each variant falls back to the default when unset..
        /// </summary>
        public static string Settings_Theme_StaticIconColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_StaticIconColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme tray icon color.
        /// </summary>
        public static string Settings_Theme_StaticIconColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_StaticIconColor_LightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static icon color.
        /// </summary>
        public static string Settings_Theme_StaticIconColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_StaticIconColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme text color.
        /// </summary>
        public static string Settings_Theme_TextColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_TextColor_DarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the default text color. Each variant falls back to the default when unset..
        /// </summary>
        public static string Settings_Theme_TextColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_TextColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme text color.
        /// </summary>
        public static string Settings_Theme_TextColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_TextColor_LightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        public static string Settings_Theme_TextColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_TextColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_ThemeStyle_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Windows, or force light / dark mode for this app..
        /// </summary>
        public static string Settings_Theme_ThemeStyle_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_ThemeStyle_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Settings_Theme_ThemeStyle_System {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme style.
        /// </summary>
        public static string Settings_Theme_ThemeStyle_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon.
        /// </summary>
        public static string Settings_Theme_TrayIcon_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_TrayIcon_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt + double left click.
        /// </summary>
        public static string Settings_TrayIcon_AltDoubleLeftClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_AltDoubleLeftClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt + left click.
        /// </summary>
        public static string Settings_TrayIcon_AltLeftClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_AltLeftClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt + right click.
        /// </summary>
        public static string Settings_TrayIcon_AltRightClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_AltRightClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string Settings_TrayIcon_ClickAction_Nothing {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ClickAction_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        public static string Settings_TrayIcon_ClickAction_OpenSettings {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ClickAction_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu.
        /// </summary>
        public static string Settings_TrayIcon_ContextMenu_Header {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ContextMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + double left click.
        /// </summary>
        public static string Settings_TrayIcon_CtrlDoubleLeftClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_CtrlDoubleLeftClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + left click.
        /// </summary>
        public static string Settings_TrayIcon_CtrlLeftClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_CtrlLeftClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + right click.
        /// </summary>
        public static string Settings_TrayIcon_CtrlRightClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_CtrlRightClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double left click.
        /// </summary>
        public static string Settings_TrayIcon_DoubleLeftClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_DoubleLeftClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string Settings_TrayIcon_MenuPosition_Classic {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_MenuPosition_Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic opens at the cursor. Modern docks the menu above the taskbar like the Windows 11 system flyouts..
        /// </summary>
        public static string Settings_TrayIcon_MenuPosition_Description {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_MenuPosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern.
        /// </summary>
        public static string Settings_TrayIcon_MenuPosition_Modern {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_MenuPosition_Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu position.
        /// </summary>
        public static string Settings_TrayIcon_MenuPosition_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_MenuPosition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign actions to modified clicks on the tray icon. Entries set to Nothing fall back to the default behavior..
        /// </summary>
        public static string Settings_TrayIcon_ModifiedActions_Description {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ModifiedActions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified actions.
        /// </summary>
        public static string Settings_TrayIcon_ModifiedActions_Header {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ModifiedActions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable scrolling the mouse wheel while hovering the tray icon. Does *not* use an always-active global mouse hook..
        /// </summary>
        public static string Settings_TrayIcon_MouseWheel_Description {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_MouseWheel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse wheel.
        /// </summary>
        public static string Settings_TrayIcon_MouseWheel_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_MouseWheel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray Icon.
        /// </summary>
        public static string Settings_TrayIcon_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append the current CPU package temperature to the tray icon tooltip..
        /// </summary>
        public static string Settings_TrayIcon_ShowCPUTemp_Description {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ShowCPUTemp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show CPU temperature.
        /// </summary>
        public static string Settings_TrayIcon_ShowCPUTemp_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ShowCPUTemp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append the current GPU core temperature to the tray icon tooltip..
        /// </summary>
        public static string Settings_TrayIcon_ShowGPUTemp_Description {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ShowGPUTemp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show GPU temperature.
        /// </summary>
        public static string Settings_TrayIcon_ShowGPUTemp_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ShowGPUTemp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip.
        /// </summary>
        public static string Settings_TrayIcon_Tooltip_Header {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_Tooltip_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SettingsWindow_Caption_Close {
            get {
                return ResourceManager.GetString("SettingsWindow_Caption_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string SettingsWindow_Caption_Maximize {
            get {
                return ResourceManager.GetString("SettingsWindow_Caption_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string SettingsWindow_Caption_Minimize {
            get {
                return ResourceManager.GetString("SettingsWindow_Caption_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsWindow_ConfirmOverlay_Cancel {
            get {
                return ResourceManager.GetString("SettingsWindow_ConfirmOverlay_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string SettingsWindow_ConfirmOverlay_Confirm {
            get {
                return ResourceManager.GetString("SettingsWindow_ConfirmOverlay_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string SettingsWindow_ConfirmOverlay_DefaultMessage {
            get {
                return ResourceManager.GetString("SettingsWindow_ConfirmOverlay_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all saved display data?.
        /// </summary>
        public static string SettingsWindow_ConfirmOverlay_DefaultTitle {
            get {
                return ResourceManager.GetString("SettingsWindow_ConfirmOverlay_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings folder.
        /// </summary>
        public static string SettingsWindow_OpenSettingsFolder {
            get {
                return ResourceManager.GetString("SettingsWindow_OpenSettingsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Tray_Settings {
            get {
                return ResourceManager.GetString("Tray_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Temp: {0}C.
        /// </summary>
        public static string Tray_Tooltip_CPUTemp_Format {
            get {
                return ResourceManager.GetString("Tray_Tooltip_CPUTemp_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FanControlTrayAppDotNET.
        /// </summary>
        public static string Tray_Tooltip_Default {
            get {
                return ResourceManager.GetString("Tray_Tooltip_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Temp: {0}C.
        /// </summary>
        public static string Tray_Tooltip_GPUTemp_Format {
            get {
                return ResourceManager.GetString("Tray_Tooltip_GPUTemp_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Uninstaller_Cancel {
            get {
                return ResourceManager.GetString("Uninstaller_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Uninstaller_Caption_Close {
            get {
                return ResourceManager.GetString("Uninstaller_Caption_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will remove the installed copy of FanControlTrayAppDotNET and its registration in Windows Apps. Choose what to do with your settings..
        /// </summary>
        public static string Uninstaller_DefaultDescription {
            get {
                return ResourceManager.GetString("Uninstaller_DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also remove %LOCALAPPDATA%\TrayAppDotNET\FanControlTrayAppDotNET, including settings.xml..
        /// </summary>
        public static string Uninstaller_DeleteSettings_DefaultDescription {
            get {
                return ResourceManager.GetString("Uninstaller_DeleteSettings_DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also remove &quot;{0}&quot; including settings.xml..
        /// </summary>
        public static string Uninstaller_DeleteSettings_Description_Format {
            get {
                return ResourceManager.GetString("Uninstaller_DeleteSettings_Description_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete my settings.
        /// </summary>
        public static string Uninstaller_DeleteSettings_Title {
            get {
                return ResourceManager.GetString("Uninstaller_DeleteSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will remove FanControlTrayAppDotNET installed at &quot;{0}&quot; and its entry in Windows Settings &gt; Apps. Choose what to do with your settings..
        /// </summary>
        public static string Uninstaller_Description_Format {
            get {
                return ResourceManager.GetString("Uninstaller_Description_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave settings.xml in place so a future install picks them up..
        /// </summary>
        public static string Uninstaller_KeepSettings_Description {
            get {
                return ResourceManager.GetString("Uninstaller_KeepSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep my settings.
        /// </summary>
        public static string Uninstaller_KeepSettings_Title {
            get {
                return ResourceManager.GetString("Uninstaller_KeepSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall FanControlTrayAppDotNET.
        /// </summary>
        public static string Uninstaller_SectionHeader {
            get {
                return ResourceManager.GetString("Uninstaller_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall FanControlTrayAppDotNET.
        /// </summary>
        public static string Uninstaller_Title {
            get {
                return ResourceManager.GetString("Uninstaller_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstaller_UninstallButton {
            get {
                return ResourceManager.GetString("Uninstaller_UninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        public static string Uninstaller_UninstallingButton {
            get {
                return ResourceManager.GetString("Uninstaller_UninstallingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UpdateDialog_Cancel {
            get {
                return ResourceManager.GetString("UpdateDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string UpdateDialog_CaptionClose_Tooltip {
            get {
                return ResourceManager.GetString("UpdateDialog_CaptionClose_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer release is available. Install it to update the running app..
        /// </summary>
        public static string UpdateDialog_DefaultDescription {
            get {
                return ResourceManager.GetString("UpdateDialog_DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string UpdateDialog_DefaultTitle {
            get {
                return ResourceManager.GetString("UpdateDialog_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string UpdateDialog_Install {
            get {
                return ResourceManager.GetString("UpdateDialog_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no changelog provided).
        /// </summary>
        public static string UpdateDialog_NoChangelog {
            get {
                return ResourceManager.GetString("UpdateDialog_NoChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available: {0}.
        /// </summary>
        public static string UpdateDialog_TitleFormat {
            get {
                return ResourceManager.GetString("UpdateDialog_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is available. Click to open update actions..
        /// </summary>
        public static string UpdateNotification_BodyFormat {
            get {
                return ResourceManager.GetString("UpdateNotification_BodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string UpdateNotification_Title {
            get {
                return ResourceManager.GetString("UpdateNotification_Title", resourceCulture);
            }
        }
    }
}
