<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <TrayAppDotNETIsSharedBuildProject>true</TrayAppDotNETIsSharedBuildProject>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <NoWarn>$(NoWarn);RS1036;RS2008;RS1041</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
