using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TrayAppDotNETCommon.XmlSourceGenerator;

[Generator]
public sealed class TrayXmlSourceGenerator : IIncrementalGenerator
{
    private const string GeneratedFileName = "TrayXml.Generated.g.cs";
    private const string XmlRootAttribute = "System.Xml.Serialization.XmlRootAttribute";
    private const string XmlAttributeAttribute = "System.Xml.Serialization.XmlAttributeAttribute";
    private const string XmlElementAttribute = "System.Xml.Serialization.XmlElementAttribute";
    private const string XmlArrayAttribute = "System.Xml.Serialization.XmlArrayAttribute";
    private const string XmlArrayItemAttribute = "System.Xml.Serialization.XmlArrayItemAttribute";
    private const string XmlIgnoreAttribute = "System.Xml.Serialization.XmlIgnoreAttribute";

    private static readonly DiagnosticDescriptor UnsupportedMember = new(
        "TAXML001",
        "Unsupported XML-serializable member",
        "Member '{0}' has unsupported XML serialization type '{1}'. Add [XmlIgnore] or adjust the type.",
        "TrayXml",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> roots = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                XmlRootAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(roots.Collect(), static (spc, source) =>
        {
            HashSet<INamedTypeSymbol> seen = new(SymbolEqualityComparer.Default);
            List<INamedTypeSymbol> rootTypes = [];
            rootTypes.AddRange(source.Where(seen.Add));

            if (rootTypes.Count == 0) return;

            GeneratorModel model = new(spc);
            foreach (INamedTypeSymbol root in rootTypes)
                model.AddRoot(root);

            spc.AddSource(GeneratedFileName, model.Generate());
        });
    }

    private sealed class GeneratorModel(SourceProductionContext context)
    {
        private readonly Dictionary<INamedTypeSymbol, TypeInfo> _types = new(SymbolEqualityComparer.Default);
        private readonly Queue<INamedTypeSymbol> _pending = new();
        private readonly List<INamedTypeSymbol> _roots = [];
        private int _nextTypeId;

        public void AddRoot(INamedTypeSymbol type)
        {
            if (!_roots.Contains(type, SymbolEqualityComparer.Default))
                _roots.Add(type);

            Enqueue(type);
            Drain();
        }

        private void Enqueue(INamedTypeSymbol type)
        {
            if (_types.ContainsKey(type)) return;

            TypeInfo info = new(type, $"T{_nextTypeId++}", GetRootName(type));
            _types[type] = info;
            _pending.Enqueue(type);
        }

        private void Drain()
        {
            while (_pending.Count > 0)
            {
                INamedTypeSymbol type = _pending.Dequeue();
                TypeInfo info = _types[type];

                foreach (IPropertySymbol property in SerializableProperties(type))
                {
                    MemberInfo? member = CreateMember(property);
                    if (member == null) continue;

                    info.Members.Add(member);
                    ITypeSymbol valueType = member.ItemType ?? member.Type;
                    if (IsComplex(valueType) && valueType is INamedTypeSymbol named)
                        Enqueue(named);
                }
            }
        }

        public string Generate()
        {
            string registrations = string.Concat(_roots.Select(root =>
                $"        TrayXmlSerializer.Register(new Serializer_{_types[root].Id}());{Environment.NewLine}"));
            string typeHelpers = string.Concat(_types.Values.Select(TypeHelpersSource));
            string rootSerializers = string.Concat(_roots.Select(root => RootSerializerSource(_types[root])));

            return
                $$"""
                // <auto-generated/>
                #nullable enable
                using System;
                using System.Collections.Generic;
                using System.Globalization;
                using System.IO;
                using System.Runtime.CompilerServices;
                using System.Xml;
                using TrayAppDotNETCommon.Serialization;

                namespace TrayAppDotNET.GeneratedXml;

                internal static class TrayXmlGeneratedSerializers
                {
                    [ModuleInitializer]
                    internal static void Register()
                    {
                {{registrations}}    }

                {{CommonHelpersSource()}}{{typeHelpers}}{{rootSerializers}}}
                """;
        }

        private static string CommonHelpersSource() =>
            """
                private static void Flush(Stream stream)
                {
                    if (stream is FileStream fileStream) fileStream.Flush(flushToDisk: true);
                    else stream.Flush();
                }

                private static string F(string? value) => value ?? string.Empty;
                private static string F(bool value) => XmlConvert.ToString(value);
                private static string F(int value) => XmlConvert.ToString(value);
                private static string F(uint value) => XmlConvert.ToString(value);
                private static string F(long value) => XmlConvert.ToString(value);
                private static string F(double value) => XmlConvert.ToString(value);
                private static string F(DateTime value) => XmlConvert.ToString(value, XmlDateTimeSerializationMode.RoundtripKind);
                private static string F<TEnum>(TEnum value) where TEnum : struct, Enum => value.ToString();

                private static bool P(string? value, bool fallback) { try { return value == null ? fallback : XmlConvert.ToBoolean(value); } catch { return fallback; } }
                private static int P(string? value, int fallback) { try { return value == null ? fallback : XmlConvert.ToInt32(value); } catch { return fallback; } }
                private static uint P(string? value, uint fallback) { try { return value == null ? fallback : XmlConvert.ToUInt32(value); } catch { return fallback; } }
                private static long P(string? value, long fallback) { try { return value == null ? fallback : XmlConvert.ToInt64(value); } catch { return fallback; } }
                private static double P(string? value, double fallback) { try { return value == null ? fallback : XmlConvert.ToDouble(value); } catch { return fallback; } }
                private static DateTime P(string? value, DateTime fallback) { try { return value == null ? fallback : XmlConvert.ToDateTime(value, XmlDateTimeSerializationMode.RoundtripKind); } catch { return fallback; } }
                private static string P(string? value, string? fallback) => value ?? fallback ?? string.Empty;
                private static string? PNString(string? value, string? fallback) => value ?? fallback;
                private static TEnum P<TEnum>(string? value, TEnum fallback) where TEnum : struct, Enum => Enum.TryParse(value, ignoreCase: false, out TEnum parsed) ? parsed : fallback;
                private static bool? PNBool(string? value) => string.IsNullOrEmpty(value) ? null : P(value, default(bool));
                private static int? PNInt32(string? value) => string.IsNullOrEmpty(value) ? null : P(value, default(int));
                private static uint? PNUInt32(string? value) => string.IsNullOrEmpty(value) ? null : P(value, default(uint));
                private static long? PNInt64(string? value) => string.IsNullOrEmpty(value) ? null : P(value, default(long));
                private static double? PNDouble(string? value) => string.IsNullOrEmpty(value) ? null : P(value, default(double));
                private static DateTime? PNDateTime(string? value) => string.IsNullOrEmpty(value) ? null : P(value, default(DateTime));
                private static TEnum? PNEnum<TEnum>(string? value) where TEnum : struct, Enum => string.IsNullOrEmpty(value) ? null : P<TEnum>(value, default);

            """ + Environment.NewLine;

        private string TypeHelpersSource(TypeInfo info)
        {
            string typeName = TypeName(info.Type);
            string writeBody = string.Concat(info.Members
                .Where(static m => m.Shape == MemberShape.Attribute)
                .Select(WriteAttributeSource)
                .Concat(info.Members
                    .Where(static m => m.Shape != MemberShape.Attribute)
                    .Select(WriteElementSource)));
            string readAttributes = string.Concat(info.Members
                .Where(static m => m.Shape == MemberShape.Attribute)
                .Select(ReadAttributeSource));
            string readCases = string.Concat(info.Members
                .Where(static m => m.Shape != MemberShape.Attribute)
                .Select(member => ReadElementCaseSource(info, member)));
            string readArrayHelpers = string.Concat(info.Members
                .Where(static m => m.IsCollection && m.Shape == MemberShape.Array)
                .Select(member => ReadArrayHelperSource(info, member)));

            return
                $$"""
                    private static void Write_{{info.Id}}(XmlWriter writer, {{typeName}} value, string elementName)
                    {
                        if ((object)value is ITrayXmlSerializationCallbacks callbacks) callbacks.OnTrayXmlSerializing();
                        writer.WriteStartElement(elementName);
                {{writeBody}}        writer.WriteEndElement();
                    }

                    private static {{typeName}} Read_{{info.Id}}(XmlReader reader)
                    {
                        {{typeName}} value = new();
                        if ((object)value is ITrayXmlSerializationCallbacks callbacks) callbacks.OnTrayXmlDeserializing();
                {{readAttributes}}        bool isEmpty = reader.IsEmptyElement;
                        reader.ReadStartElement();
                        if (!isEmpty)
                        {
                            while (reader.NodeType != XmlNodeType.EndElement)
                            {
                                if (reader.NodeType != XmlNodeType.Element)
                                {
                                    if (!reader.Read()) break;
                                    continue;
                                }

                                switch (reader.LocalName)
                                {
                {{readCases}}                default:
                                        reader.Skip();
                                        break;
                                }
                            }

                            if (reader.NodeType == XmlNodeType.EndElement) reader.ReadEndElement();
                        }

                        if ((object)value is ITrayXmlSerializationCallbacks callbacksAfter) callbacksAfter.OnTrayXmlDeserialized();
                        return value;
                    }

                {{readArrayHelpers}}
                """ + Environment.NewLine;
        }

        private static string RootSerializerSource(TypeInfo info)
        {
            string typeName = TypeName(info.Type);
            return
                $$"""
                    private sealed class Serializer_{{info.Id}} : ITrayXmlTypeSerializer
                    {
                        public Type TargetType => typeof({{typeName}});

                        public object Read(Stream stream)
                        {
                            using XmlReader reader = XmlReader.Create(stream, TrayXmlSerializer.ReaderSettings);
                            reader.MoveToContent();
                            if (reader.NodeType != XmlNodeType.Element || reader.LocalName != {{Literal(info.RootName)}})
                                throw new InvalidDataException({{Literal($"Unexpected XML root for {typeName}.")}});

                            return Read_{{info.Id}}(reader);
                        }

                        public void Write(Stream stream, object value)
                        {
                            using XmlWriter writer = XmlWriter.Create(stream, TrayXmlSerializer.WriterSettings);
                            Write_{{info.Id}}(writer, ({{typeName}})value, {{Literal(info.RootName)}});
                            writer.Flush();
                            Flush(stream);
                        }
                    }

                """ + Environment.NewLine;
        }

        private static string WriteAttributeSource(MemberInfo member)
        {
            string access = $"value.{Identifier(member.Property.Name)}";
            if (IsNullableValue(member.Type))
            {
                ITypeSymbol underlying = Nullable.GetUnderlyingTypeSymbol(member.Type)!;
                string formatted = FormatExpression($"{access}.Value", underlying);
                return $"        if ({access}.HasValue) writer.WriteAttributeString({Literal(member.Name)}, {formatted});{Environment.NewLine}";
            }

            string prefix = IsNullableReference(member.Type) ? $"if ({access} != null) " : string.Empty;
            return $"        {prefix}writer.WriteAttributeString({Literal(member.Name)}, {FormatExpression(access, member.Type)});{Environment.NewLine}";
        }

        private static string ReadAttributeSource(MemberInfo member)
        {
            string propertyName = Identifier(member.Property.Name);
            string attrVar = $"attr_{member.Property.Name}";
            string parsed = ParseExpression(attrVar, member.Type, $"value.{propertyName}");
            return
                $"""
                        string? {attrVar} = reader.GetAttribute({Literal(member.Name)});
                        if ({attrVar} != null) value.{propertyName} = {parsed};
                """ + Environment.NewLine;
        }

        private string WriteElementSource(MemberInfo member)
        {
            string propertyName = Identifier(member.Property.Name);
            string access = $"value.{propertyName}";

            return member.IsCollection
                ? WriteCollectionSource(member, access)
                : WriteValueSource(member.Type, access, member.Name, "        ");
        }

        private string WriteCollectionSource(MemberInfo member, string access)
        {
            ITypeSymbol itemType = member.ItemType!;
            bool wrapsItems = member.Shape == MemberShape.Array;
            string itemName = wrapsItems ? member.ItemName : member.Name;
            string startElement = wrapsItems ? $"        writer.WriteStartElement({Literal(member.Name)});{Environment.NewLine}" : string.Empty;
            string endElement = wrapsItems ? $"{Environment.NewLine}{Environment.NewLine}        writer.WriteEndElement();" : string.Empty;
            string writeItem = WriteValueSource(itemType, "item", itemName, "                ");

            return
                $$"""
                {{startElement}}        if ({{access}} != null)
                        {
                            foreach ({{TypeName(itemType)}} item in {{access}})
                            {
                {{writeItem}}
                            }
                        }{{endElement}}
                """ + Environment.NewLine;
        }

        private string WriteValueSource(ITypeSymbol itemType, string itemExpression, string elementName, string indent)
        {
            if (!IsComplex(itemType))
            {
                return
                    $"{indent}writer.WriteElementString({Literal(elementName)}, {FormatExpression(itemExpression, itemType)});{Environment.NewLine}";
            }

            string writeCall = $"Write_{_types[(INamedTypeSymbol)itemType].Id}(writer, {itemExpression}, {Literal(elementName)});";
            if (itemType.IsValueType)
                return $"{indent}{writeCall}{Environment.NewLine}";

            return
                $"""
                 {indent}if ({itemExpression} != null)
                 {indent}    {writeCall}
                 """ + Environment.NewLine;

        }

        private string ReadElementCaseSource(TypeInfo info, MemberInfo member)
        {
            string propertyName = Identifier(member.Property.Name);
            string body;

            if (member is { IsCollection: true, Shape: MemberShape.Array })
            {
                body = $"                    value.{propertyName} = ReadList_{info.Id}_{member.Property.Name}(reader);";
            }
            else if (member.IsCollection)
            {
                ITypeSymbol itemType = member.ItemType!;
                body =
                    $"""
                                        value.{propertyName} ??= new {TypeName(member.Type)}();
                                        value.{propertyName}.Add({ReadItemExpression(itemType, "reader")});
                    """;
            }
            else
            {
                string readExpression = IsComplex(member.Type)
                    ? $"Read_{_types[(INamedTypeSymbol)member.Type].Id}(reader)"
                    : ParseExpression("reader.ReadElementContentAsString()", member.Type, $"value.{propertyName}");

                body = $"                    value.{propertyName} = {readExpression};";
            }

            return
                $"""
                                    case {Literal(member.Name)}:
                {body}
                                        break;
                """ + Environment.NewLine;
        }

        private string ReadArrayHelperSource(TypeInfo info, MemberInfo member)
        {
            ITypeSymbol itemType = member.ItemType!;
            return
                $$"""
                    private static {{TypeName(member.Type)}} ReadList_{{info.Id}}_{{member.Property.Name}}(XmlReader reader)
                    {
                        {{TypeName(member.Type)}} list = new();
                        bool isEmpty = reader.IsEmptyElement;
                        reader.ReadStartElement();
                        if (isEmpty) return list;

                        while (reader.NodeType != XmlNodeType.EndElement)
                        {
                            if (reader.NodeType != XmlNodeType.Element)
                            {
                                if (!reader.Read()) break;
                                continue;
                            }

                            if (reader.LocalName == {{Literal(member.ItemName)}}) list.Add({{ReadItemExpression(itemType, "reader")}});
                            else reader.Skip();
                        }

                        if (reader.NodeType == XmlNodeType.EndElement) reader.ReadEndElement();
                        return list;
                    }

                """ + Environment.NewLine;
        }

        private string ReadItemExpression(ITypeSymbol itemType, string readerExpression) =>
            IsComplex(itemType)
                ? $"Read_{_types[(INamedTypeSymbol)itemType].Id}({readerExpression})"
                : ParseExpression($"{readerExpression}.ReadElementContentAsString()", itemType, DefaultExpression(itemType));

        private MemberInfo? CreateMember(IPropertySymbol property)
        {
            ITypeSymbol type = property.Type;
            bool isCollection = TryGetListItemType(type, out ITypeSymbol? itemType);
            ITypeSymbol validateType = itemType ?? type;

            if (!IsSupported(validateType))
            {
                ReportUnsupported(property, validateType);
                return null;
            }

            AttributeData? attr = FindAttribute(property, XmlAttributeAttribute);
            if (attr != null)
            {
                if (isCollection || !IsAttributeType(type))
                {
                    ReportUnsupported(property, type);
                    return null;
                }

                return new MemberInfo(
                    property,
                    type,
                    MemberShape.Attribute,
                    AttributeName(attr, property.Name),
                    itemName: string.Empty,
                    itemType);
            }

            AttributeData? array = FindAttribute(property, XmlArrayAttribute);
            AttributeData? element = FindAttribute(property, XmlElementAttribute);

            if (isCollection)
            {
                if (element != null)
                {
                    string collectionElementName = AttributeName(element, property.Name);
                    return new MemberInfo(
                        property,
                        type,
                        MemberShape.Element,
                        collectionElementName,
                        collectionElementName,
                        itemType);
                }

                string itemName = GetItemName(property, itemType);
                string wrapperName = array != null ? AttributeName(array, property.Name) : property.Name;
                return new MemberInfo(property, type, MemberShape.Array, wrapperName, itemName, itemType);
            }

            string elementName = element != null ? AttributeName(element, property.Name) : property.Name;
            return new MemberInfo(property, type, MemberShape.Element, elementName, itemName: string.Empty, itemType);
        }

        private void ReportUnsupported(IPropertySymbol property, ITypeSymbol type)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                UnsupportedMember,
                property.Locations.FirstOrDefault(),
                property.ToDisplayString(),
                type.ToDisplayString()));
        }

        private static IEnumerable<IPropertySymbol> SerializableProperties(INamedTypeSymbol type)
        {
            Stack<INamedTypeSymbol> hierarchy = new();
            for (INamedTypeSymbol? current = type;
                 current != null && current.SpecialType != SpecialType.System_Object;
                 current = current.BaseType)
            {
                hierarchy.Push(current);
            }

            HashSet<string> seen = [];
            while (hierarchy.Count > 0)
            {
                INamedTypeSymbol current = hierarchy.Pop();
                foreach (IPropertySymbol property in current.GetMembers().OfType<IPropertySymbol>())
                {
                    if (!seen.Add(property.Name)) continue;
                    if (property.IsStatic) continue;
                    if (property.Parameters.Length != 0) continue;
                    if (property.GetMethod == null || property.SetMethod == null) continue;
                    if (property.GetMethod.DeclaredAccessibility != Accessibility.Public
                        || property.SetMethod.DeclaredAccessibility != Accessibility.Public)
                        continue;
                    if (HasAttribute(property, XmlIgnoreAttribute)) continue;

                    yield return property;
                }
            }
        }

        private static bool TryGetListItemType(ITypeSymbol type, out ITypeSymbol? itemType)
        {
            itemType = null;
            if (type is not INamedTypeSymbol { IsGenericType: true } named
                || named.ConstructedFrom.ToDisplayString() != "System.Collections.Generic.List<T>")
                return false;

            itemType = named.TypeArguments[0];
            return true;
        }
    }

    private sealed class TypeInfo(INamedTypeSymbol type, string id, string rootName)
    {
        public INamedTypeSymbol Type { get; } = type;
        public string Id { get; } = id;
        public string RootName { get; } = rootName;
        public List<MemberInfo> Members { get; } = [];
    }

    private sealed class MemberInfo(
        IPropertySymbol property,
        ITypeSymbol type,
        MemberShape shape,
        string name,
        string itemName,
        ITypeSymbol? itemType)
    {
        public IPropertySymbol Property { get; } = property;
        public ITypeSymbol Type { get; } = type;
        public MemberShape Shape { get; } = shape;
        public string Name { get; } = name;
        public string ItemName { get; } = itemName;
        public ITypeSymbol? ItemType { get; } = itemType;
        public bool IsCollection => ItemType != null;
    }

    private enum MemberShape
    {
        Element,
        Attribute,
        Array,
    }

    private static string FormatExpression(string expression, ITypeSymbol type)
    {
        if (IsNullableValue(type))
        {
            ITypeSymbol underlying = Nullable.GetUnderlyingTypeSymbol(type)!;
            return $"{expression}.HasValue ? {FormatExpression($"{expression}.Value", underlying)} : string.Empty";
        }

        if (type.SpecialType == SpecialType.System_String
            || type.SpecialType == SpecialType.System_Boolean
            || type.SpecialType == SpecialType.System_Int32
            || type.SpecialType == SpecialType.System_UInt32
            || type.SpecialType == SpecialType.System_Int64
            || type.SpecialType == SpecialType.System_Double
            || type.TypeKind == TypeKind.Enum
            || IsDateTime(type))
            return $"F({expression})";

        return $"F({expression}.ToString())";
    }

    private static string ParseExpression(string valueExpression, ITypeSymbol type, string fallbackExpression)
    {
        if (IsNullableValue(type))
        {
            ITypeSymbol underlying = Nullable.GetUnderlyingTypeSymbol(type)!;
            if (underlying.TypeKind == TypeKind.Enum)
                return $"PNEnum<{TypeName(underlying)}>({valueExpression})";

            return underlying.SpecialType switch
            {
                SpecialType.System_Boolean => $"PNBool({valueExpression})",
                SpecialType.System_Int32 => $"PNInt32({valueExpression})",
                SpecialType.System_UInt32 => $"PNUInt32({valueExpression})",
                SpecialType.System_Int64 => $"PNInt64({valueExpression})",
                SpecialType.System_Double => $"PNDouble({valueExpression})",
                _ => IsDateTime(underlying) ? $"PNDateTime({valueExpression})" : "null",
            };
        }

        if (type.TypeKind == TypeKind.Enum)
            return $"P<{TypeName(type)}>({valueExpression}, {fallbackExpression})";

        return type.SpecialType switch
        {
            SpecialType.System_String => IsNullableReference(type)
                ? $"PNString({valueExpression}, {fallbackExpression})"
                : $"P({valueExpression}, {fallbackExpression} ?? string.Empty)",
            SpecialType.System_Boolean or SpecialType.System_Int32 or SpecialType.System_UInt32
                or SpecialType.System_Int64
                or SpecialType.System_Double => $"P({valueExpression}, {fallbackExpression})",
            _ => IsDateTime(type) ? $"P({valueExpression}, {fallbackExpression})" : fallbackExpression,
        };
    }

    private static bool IsSupported(ITypeSymbol type)
    {
        if (IsNullableValue(type)) type = Nullable.GetUnderlyingTypeSymbol(type)!;
        return IsSimple(type) || IsComplex(type);
    }

    private static bool IsAttributeType(ITypeSymbol type)
    {
        if (IsNullableValue(type)) type = Nullable.GetUnderlyingTypeSymbol(type)!;
        return IsSimple(type);
    }

    private static bool IsSimple(ITypeSymbol type) =>
        type.SpecialType is SpecialType.System_String
            or SpecialType.System_Boolean
            or SpecialType.System_Int32
            or SpecialType.System_UInt32
            or SpecialType.System_Int64
            or SpecialType.System_Double
        || type.TypeKind == TypeKind.Enum
        || IsDateTime(type);

    private static bool IsComplex(ITypeSymbol type)
    {
        if (IsNullableValue(type)) return false;
        if (IsSimple(type)) return false;
        if (type is not INamedTypeSymbol named) return false;
        if (named.TypeKind is not (TypeKind.Class or TypeKind.Struct)) return false;

        return named.ContainingNamespace?.ToDisplayString().StartsWith("System", StringComparison.Ordinal) != true
            && HasPublicParameterlessConstructor(named);
    }

    private static bool HasPublicParameterlessConstructor(INamedTypeSymbol type)
    {
        if (type.TypeKind == TypeKind.Struct) return true;

        return type.InstanceConstructors.Any(static ctor =>
            ctor.Parameters.Length == 0 && ctor.DeclaredAccessibility == Accessibility.Public);
    }

    private static string GetItemName(IPropertySymbol property, ITypeSymbol? itemType)
    {
        AttributeData? item = FindAttribute(property, XmlArrayItemAttribute);
        if (item != null) return AttributeName(item, itemType?.Name ?? "Item");

        return itemType?.SpecialType == SpecialType.System_String
            ? "Item"
            : itemType?.Name ?? "Item";
    }

    private static bool HasAttribute(ISymbol symbol, string metadataName) =>
        FindAttribute(symbol, metadataName) != null;

    private static AttributeData? FindAttribute(ISymbol symbol, string metadataName) =>
        symbol.GetAttributes().FirstOrDefault(attr =>
            attr.AttributeClass?.ToDisplayString() == metadataName);

    private static string GetRootName(INamedTypeSymbol type)
    {
        AttributeData? attr = FindAttribute(type, XmlRootAttribute);
        return attr == null ? type.Name : AttributeName(attr, type.Name);
    }

    private static string AttributeName(AttributeData attr, string fallback)
    {
        if (attr.ConstructorArguments.Length > 0
            && attr.ConstructorArguments[0].Value is string ctorValue
            && !string.IsNullOrEmpty(ctorValue))
            return ctorValue;

        foreach (KeyValuePair<string, TypedConstant> named in attr.NamedArguments)
        {
            if ((named.Key is "ElementName" or "AttributeName")
                && named.Value.Value is string value
                && !string.IsNullOrEmpty(value))
                return value;
        }

        return fallback;
    }

    private static string TypeName(ITypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string Identifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None ? name : $"@{name}";

    private static bool IsNullableReference(ITypeSymbol type) =>
        type is { NullableAnnotation: NullableAnnotation.Annotated, IsValueType: false };

    private static bool IsNullableValue(ITypeSymbol type) =>
        Nullable.GetUnderlyingTypeSymbol(type) != null;

    private static bool IsDateTime(ITypeSymbol type) =>
        type.ToDisplayString() == "System.DateTime";

    private static string DefaultExpression(ITypeSymbol type)
    {
        if (type.TypeKind == TypeKind.Enum) return $"default({TypeName(type)})";

        return type.SpecialType switch
        {
            SpecialType.System_String => "string.Empty",
            SpecialType.System_Boolean => "default(bool)",
            SpecialType.System_Int32 => "default(int)",
            SpecialType.System_UInt32 => "default(uint)",
            SpecialType.System_Int64 => "default(long)",
            SpecialType.System_Double => "default(double)",
            _ => IsDateTime(type) ? "default(DateTime)" : "default",
        };
    }

    private static string Literal(string value) =>
        SymbolDisplay.FormatLiteral(value, quote: true);
}

internal static class Nullable
{
    public static ITypeSymbol? GetUnderlyingTypeSymbol(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol { IsGenericType: true, ConstructedFrom.SpecialType: SpecialType.System_Nullable_T } named)
            return named.TypeArguments[0];

        return null;
    }
}
