#pragma once

#define DDC_HELPER_MODE_ARGUMENT L"--ddc-helper-server"
#define DDC_HELPER_PARENT_PROCESS_ID_ARGUMENT L"--parent-pid"
#define DDC_HELPER_PIPE_NAME_ARGUMENT L"--pipe-name"
#define DDC_HELPER_EXIT_COMMAND "EXIT"
#define DDC_HELPER_PING_COMMAND "PING"
#define DDC_HELPER_READY_RESPONSE "READY\t1"
#define DDC_HELPER_PING_RESPONSE "OK\tPONG\t1"
#define DDC_HELPER_CONNECT_TIMEOUT_MS 5000U
#define DDC_HELPER_MAX_COMMAND_BYTES 65536U
#define DDC_HELPER_MAX_CAPABILITIES_BYTES 1048576U
