namespace TrayAppDotNET.Tools.AppIconGenerator;

/// <summary>Describes one normalized SVG layer in an application icon.</summary>
internal readonly record struct SVGIconLayer(string ResourceFileName, NormalizedRectangle Destination);

/// <summary>Describes a rectangle in the composition's zero-to-one design canvas.</summary>
internal readonly record struct NormalizedRectangle(float X, float Y, float Width, float Height)
{
    public static readonly NormalizedRectangle FullCanvas = new(X: 0, Y: 0, Width: 1, Height: 1);
}

/// <summary>Maps an icon composition to one tray application project.</summary>
internal sealed class IconTarget(
    string shortName,
    string projectDirectoryName,
    IReadOnlyList<SVGIconLayer> layers)
{
    public readonly string ShortName = shortName;
    public readonly string ProjectDirectoryName = projectDirectoryName;
    public readonly IReadOnlyList<SVGIconLayer> Layers = layers;

    /// <summary>Returns whether a command-line target name identifies this target.</summary>
    public bool Matches(string targetName) =>
        string.Equals(ShortName, targetName, StringComparison.OrdinalIgnoreCase)
        || string.Equals(ProjectDirectoryName, targetName, StringComparison.OrdinalIgnoreCase);
}

/// <summary>Defines every application icon generated by this tool.</summary>
internal static class IconTargetCatalog
{
    private const string BatterySVG = "ic_fluent_battery_6_24_regular.svg";
    private const string BrightnessSVG = "ic_fluent_brightness_high_20_filled.svg";
    private const string FanControlSVG = "fan_first_good_attempt4_onverted.svg";
    private const string NetworkSVG = "ic_fluent_desktop_signal_20_regular.svg";
    private const string TaskManagerDesktopTowerSVG = "ic_fluent_desktop_tower_20_regular.svg";
    private const string TaskManagerPulseSVG = "ic_fluent_pulse_20_regular.svg";
    private const string VolumeSVG = "ic_fluent_speaker_2_24_regular.svg";

    // Fits the pulse inside the Desktop Tower SVG's monitor content rectangle
    private static readonly NormalizedRectangle TaskManagerPulseDestination = new(
        X: 0.2625f,
        Y: 2.0f / 7.0f,
        Width: 0.625f,
        Height: 3.0f / 7.0f);

    /// <summary>Creates the complete target catalog in stable output order.</summary>
    public static IReadOnlyList<IconTarget> Create()
    {
        List<IconTarget> targets = new(capacity: 6);
        targets.Add(SingleLayerTarget("BATADN", "BatteryTrayAppDotNET", BatterySVG));
        targets.Add(SingleLayerTarget("BTADN", "BrightnessTrayAppDotNET", BrightnessSVG));
        targets.Add(SingleLayerTarget("FCTADN", "FanControlTrayAppDotNET", FanControlSVG));
        targets.Add(SingleLayerTarget("NTADN", "NetworkTrayAppDotNET", NetworkSVG));
        targets.Add(new IconTarget(
            "TMTADN",
            "TaskManagerTrayAppDotNET",
            [
                new SVGIconLayer(TaskManagerDesktopTowerSVG, NormalizedRectangle.FullCanvas),
                new SVGIconLayer(TaskManagerPulseSVG, TaskManagerPulseDestination)
            ]));
        targets.Add(SingleLayerTarget("VTADN", "VolumeTrayAppDotNET", VolumeSVG));
        return targets;
    }

    private static IconTarget SingleLayerTarget(string shortName, string projectDirectoryName, string SVGFileName) =>
        new(
            shortName,
            projectDirectoryName,
            [new SVGIconLayer(SVGFileName, NormalizedRectangle.FullCanvas)]);
}
