// <auto-generated/>
#nullable enable
using System.Globalization;
using System.Resources;

namespace BatteryTrayAppDotNET.Localization;

internal static class Strings
{
    private static ResourceManager? resourceMan;

    public static ResourceManager ResourceManager =>
        resourceMan ??= new ResourceManager("BatteryTrayAppDotNET.Localization.Strings", typeof(Strings).Assembly);

    public static CultureInfo? Culture { get; set; }
}
