//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryTrayAppDotNET.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryTrayAppDotNET.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color picker.
        /// </summary>
        public static string ColorPicker_DefaultTitle {
            get {
                return ResourceManager.GetString("ColorPicker_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout.
        /// </summary>
        public static string Settings_Common_Page_Flyout {
            get {
                return ResourceManager.GetString("Settings_Common_Page_Flyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the undocked flyout fully inside one monitor&apos;s work area when it restores or repositions..
        /// </summary>
        public static string Settings_Flyout_ClampUndockedToScreen_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_ClampUndockedToScreen_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep undocked flyout on screen.
        /// </summary>
        public static string Settings_Flyout_ClampUndockedToScreen_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_ClampUndockedToScreen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render the flyout title bar at the bottom of the flyout instead of the top..
        /// </summary>
        public static string Settings_Flyout_HeaderAtBottom_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_HeaderAtBottom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar at the bottom.
        /// </summary>
        public static string Settings_Flyout_HeaderAtBottom_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_HeaderAtBottom_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Settings_Flyout_Layout_Header {
            get {
                return ResourceManager.GetString("Settings_Flyout_Layout_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the app launches, restore the flyout&apos;s docked or undocked state from the previous session. When off, the flyout always opens docked..
        /// </summary>
        public static string Settings_Flyout_RestoreUndockState_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_RestoreUndockState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore undock state on startup.
        /// </summary>
        public static string Settings_Flyout_RestoreUndockState_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_RestoreUndockState_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout.
        /// </summary>
        public static string Settings_Flyout_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_Flyout_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the undock button in the flyout. When off, the flyout always stays anchored to the tray..
        /// </summary>
        public static string Settings_Flyout_ShowUndockButton_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_ShowUndockButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show undock button.
        /// </summary>
        public static string Settings_Flyout_ShowUndockButton_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_ShowUndockButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string Settings_Flyout_Visibility_Header {
            get {
                return ResourceManager.GetString("Settings_Flyout_Visibility_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not now.
        /// </summary>
        public static string Settings_General_NotNow_Button {
            get {
                return ResourceManager.GetString("Settings_General_NotNow_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        public static string Settings_General_Rendering_Header {
            get {
                return ResourceManager.GetString("Settings_General_Rendering_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU preferred.
        /// </summary>
        public static string Settings_General_RenderingBackend_GPUPreferred {
            get {
                return ResourceManager.GetString("Settings_General_RenderingBackend_GPUPreferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        public static string Settings_General_RenderingBackend_Software {
            get {
                return ResourceManager.GetString("Settings_General_RenderingBackend_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering backend.
        /// </summary>
        public static string Settings_General_RenderingBackend_Title {
            get {
                return ResourceManager.GetString("Settings_General_RenderingBackend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Settings_General_RenderingRestart_Button {
            get {
                return ResourceManager.GetString("Settings_General_RenderingRestart_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the app now to apply the selected rendering backend?.
        /// </summary>
        public static string Settings_General_RenderingRestart_Message {
            get {
                return ResourceManager.GetString("Settings_General_RenderingRestart_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        public static string Settings_General_RenderingRestart_Title {
            get {
                return ResourceManager.GetString("Settings_General_RenderingRestart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart failed.
        /// </summary>
        public static string Settings_General_RestartFailed_Title {
            get {
                return ResourceManager.GetString("Settings_General_RestartFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark flyout background.
        /// </summary>
        public static string Settings_Theme_FlyoutBackgroundColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutBackgroundColor_DarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the main battery flyout background color..
        /// </summary>
        public static string Settings_Theme_FlyoutBackgroundColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutBackgroundColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light flyout background.
        /// </summary>
        public static string Settings_Theme_FlyoutBackgroundColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutBackgroundColor_LightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout background.
        /// </summary>
        public static string Settings_Theme_FlyoutBackgroundColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutBackgroundColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark titlebar background.
        /// </summary>
        public static string Settings_Theme_FlyoutTitleBarBackgroundColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutTitleBarBackgroundColor_DarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the battery flyout titlebar background color..
        /// </summary>
        public static string Settings_Theme_FlyoutTitleBarBackgroundColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutTitleBarBackgroundColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light titlebar background.
        /// </summary>
        public static string Settings_Theme_FlyoutTitleBarBackgroundColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutTitleBarBackgroundColor_LightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titlebar background.
        /// </summary>
        public static string Settings_Theme_FlyoutTitleBarBackgroundColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_FlyoutTitleBarBackgroundColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove BatteryTrayAppDotNET from this computer..
        /// </summary>
        public static string Uninstaller_Message {
            get {
                return ResourceManager.GetString("Uninstaller_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall BatteryTrayAppDotNET.
        /// </summary>
        public static string Uninstaller_Title {
            get {
                return ResourceManager.GetString("Uninstaller_Title", resourceCulture);
            }
        }
    }
}
