//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrayAppDotNETCommon.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrayAppDotNETCommon.Localization.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backdate.
        /// </summary>
        public static string BackdateDialog_Confirm {
            get {
                return ResourceManager.GetString("BackdateDialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will replace the current version with {0} and restart the app..
        /// </summary>
        public static string BackdateDialog_DescriptionFormat {
            get {
                return ResourceManager.GetString("BackdateDialog_DescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous version could not be downloaded. Check the log for details..
        /// </summary>
        public static string BackdateDialog_DownloadFailed {
            get {
                return ResourceManager.GetString("BackdateDialog_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backdate failed.
        /// </summary>
        public static string BackdateDialog_FailedTitle {
            get {
                return ResourceManager.GetString("BackdateDialog_FailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BackdateDialog_No {
            get {
                return ResourceManager.GetString("BackdateDialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After backdating, version {0} will be offered as an update. Do you want to skip it?.
        /// </summary>
        public static string BackdateDialog_SkipCurrentDescriptionFormat {
            get {
                return ResourceManager.GetString("BackdateDialog_SkipCurrentDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip the current version?.
        /// </summary>
        public static string BackdateDialog_SkipCurrentTitle {
            get {
                return ResourceManager.GetString("BackdateDialog_SkipCurrentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backdate to {0}?.
        /// </summary>
        public static string BackdateDialog_TitleFormat {
            get {
                return ResourceManager.GetString("BackdateDialog_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BackdateDialog_Yes {
            get {
                return ResourceManager.GetString("BackdateDialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to argb hex:.
        /// </summary>
        public static string ColorPicker_ARGBHexLabel {
            get {
                return ResourceManager.GetString("ColorPicker_ARGBHexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alpha.
        /// </summary>
        public static string ColorPicker_ChannelLabel_Alpha {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        public static string ColorPicker_ChannelLabel_B {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string ColorPicker_ChannelLabel_G {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hue.
        /// </summary>
        public static string ColorPicker_ChannelLabel_Hue {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r.
        /// </summary>
        public static string ColorPicker_ChannelLabel_R {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ColorPicker_CloseTooltip {
            get {
                return ResourceManager.GetString("ColorPicker_CloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ColorPicker_DefaultButton {
            get {
                return ResourceManager.GetString("ColorPicker_DefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ColorPicker_ResetButton {
            get {
                return ResourceManager.GetString("ColorPicker_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rgba hex:.
        /// </summary>
        public static string ColorPicker_RGBAHexLabel {
            get {
                return ResourceManager.GetString("ColorPicker_RGBAHexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous available version: {0}. Installing it will restart the app..
        /// </summary>
        public static string Settings_About_Backdate_AvailableFormat {
            get {
                return ResourceManager.GetString("Settings_About_Backdate_AvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backdate.
        /// </summary>
        public static string Settings_About_Backdate_Button {
            get {
                return ResourceManager.GetString("Settings_About_Backdate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking GitHub for the previous version....
        /// </summary>
        public static string Settings_About_Backdate_Checking {
            get {
                return ResourceManager.GetString("Settings_About_Backdate_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous release could not be checked..
        /// </summary>
        public static string Settings_About_Backdate_Failed {
            get {
                return ResourceManager.GetString("Settings_About_Backdate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous release is available for this app..
        /// </summary>
        public static string Settings_About_Backdate_None {
            get {
                return ResourceManager.GetString("Settings_About_Backdate_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backdate app.
        /// </summary>
        public static string Settings_About_Backdate_Title {
            get {
                return ResourceManager.GetString("Settings_About_Backdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this release.
        /// </summary>
        public static string Settings_About_SkipUpdate_Button {
            get {
                return ResourceManager.GetString("Settings_About_SkipUpdate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release {0} skipped. You&apos;ll be notified when a newer release is available..
        /// </summary>
        public static string Settings_About_UpdateStatus_SkippedFormat {
            get {
                return ResourceManager.GetString("Settings_About_UpdateStatus_SkippedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;GPU preferred&quot; uses Avalonia&apos;s Windows GPU path with software fallback. &quot;Software&quot; forces CPU rendering. GPU rendering is faster but has more RAM overhead. Restart required..
        /// </summary>
        public static string Settings_General_RenderingBackend_Description {
            get {
                return ResourceManager.GetString("Settings_General_RenderingBackend_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dark.
        /// </summary>
        public static string Settings_Theme_PickerTitle_DarkVariant {
            get {
                return ResourceManager.GetString("Settings_Theme_PickerTitle_DarkVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string Settings_Theme_PickerTitle_Format {
            get {
                return ResourceManager.GetString("Settings_Theme_PickerTitle_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light.
        /// </summary>
        public static string Settings_Theme_PickerTitle_LightVariant {
            get {
                return ResourceManager.GetString("Settings_Theme_PickerTitle_LightVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Settings_Theme_Reset {
            get {
                return ResourceManager.GetString("Settings_Theme_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Uninstaller_Cancel {
            get {
                return ResourceManager.GetString("Uninstaller_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstaller_UninstallButton {
            get {
                return ResourceManager.GetString("Uninstaller_UninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        public static string Uninstaller_UninstallingButton {
            get {
                return ResourceManager.GetString("Uninstaller_UninstallingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this release.
        /// </summary>
        public static string UpdateDialog_SkipRelease {
            get {
                return ResourceManager.GetString("UpdateDialog_SkipRelease", resourceCulture);
            }
        }
    }
}
