//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace NetworkTrayAppDotNET.Localization {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Strings {

        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("NetworkTrayAppDotNET.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to argb hex:.
        /// </summary>
        public static string ColorPicker_ArgbHexLabel {
            get {
                return ResourceManager.GetString("ColorPicker_ArgbHexLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to alpha.
        /// </summary>
        public static string ColorPicker_ChannelLabel_Alpha {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_Alpha", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        public static string ColorPicker_ChannelLabel_B {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_B", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string ColorPicker_ChannelLabel_G {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_G", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hue.
        /// </summary>
        public static string ColorPicker_ChannelLabel_Hue {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_Hue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to r.
        /// </summary>
        public static string ColorPicker_ChannelLabel_R {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_R", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ColorPicker_CloseTooltip {
            get {
                return ResourceManager.GetString("ColorPicker_CloseTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ColorPicker_DefaultButton {
            get {
                return ResourceManager.GetString("ColorPicker_DefaultButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ColorPicker.
        /// </summary>
        public static string ColorPicker_DefaultTitle {
            get {
                return ResourceManager.GetString("ColorPicker_DefaultTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ColorPicker_ResetButton {
            get {
                return ResourceManager.GetString("ColorPicker_ResetButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to rgba hex:.
        /// </summary>
        public static string ColorPicker_RgbaHexLabel {
            get {
                return ResourceManager.GetString("ColorPicker_RgbaHexLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SettingsWindow_Caption_Close {
            get {
                return ResourceManager.GetString("SettingsWindow_Caption_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string SettingsWindow_Caption_Maximize {
            get {
                return ResourceManager.GetString("SettingsWindow_Caption_Maximize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string SettingsWindow_Caption_Minimize {
            get {
                return ResourceManager.GetString("SettingsWindow_Caption_Minimize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsWindow_ConfirmOverlay_Cancel {
            get {
                return ResourceManager.GetString("SettingsWindow_ConfirmOverlay_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string SettingsWindow_ConfirmOverlay_Confirm {
            get {
                return ResourceManager.GetString("SettingsWindow_ConfirmOverlay_Confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string SettingsWindow_ConfirmOverlay_DefaultMessage {
            get {
                return ResourceManager.GetString("SettingsWindow_ConfirmOverlay_DefaultMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear all saved display data?.
        /// </summary>
        public static string SettingsWindow_ConfirmOverlay_DefaultTitle {
            get {
                return ResourceManager.GetString("SettingsWindow_ConfirmOverlay_DefaultTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open settings folder.
        /// </summary>
        public static string SettingsWindow_OpenSettingsFolder {
            get {
                return ResourceManager.GetString("SettingsWindow_OpenSettingsFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Settings_About_AuthorLabel {
            get {
                return ResourceManager.GetString("Settings_About_AuthorLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Settings_About_BuildLabel {
            get {
                return ResourceManager.GetString("Settings_About_BuildLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string Settings_About_GithubLabel {
            get {
                return ResourceManager.GetString("Settings_About_GithubLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        public static string Settings_About_RuntimeLabel {
            get {
                return ResourceManager.GetString("Settings_About_RuntimeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_About_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_About_SectionHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network tray integration for Windows..
        /// </summary>
        public static string Settings_About_Tagline {
            get {
                return ResourceManager.GetString("Settings_About_Tagline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_Common_Page_About {
            get {
                return ResourceManager.GetString("Settings_Common_Page_About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_Common_Page_General {
            get {
                return ResourceManager.GetString("Settings_Common_Page_General", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string Settings_Common_Page_Hotkeys {
            get {
                return ResourceManager.GetString("Settings_Common_Page_Hotkeys", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Common_Page_Theme {
            get {
                return ResourceManager.GetString("Settings_Common_Page_Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Settings_General_Apply_Button {
            get {
                return ResourceManager.GetString("Settings_General_Apply_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automatically save changes..
        /// </summary>
        public static string Settings_General_Autosave_Description {
            get {
                return ResourceManager.GetString("Settings_General_Autosave_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto-save.
        /// </summary>
        public static string Settings_General_Autosave_Title {
            get {
                return ResourceManager.GetString("Settings_General_Autosave_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Settings_General_Cancel_Button {
            get {
                return ResourceManager.GetString("Settings_General_Cancel_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currently running from "{0}"..
        /// </summary>
        public static string Settings_General_CurrentlyRunning_Format {
            get {
                return ResourceManager.GetString("Settings_General_CurrentlyRunning_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This will copy the running exe to "{0}" and register it in Windows Settings &gt; Apps..
        /// </summary>
        public static string Settings_General_InstallConfirm_Message_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstallConfirm_Message_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install NetworkTrayAppDotNET?.
        /// </summary>
        public static string Settings_General_InstallConfirm_Title {
            get {
                return ResourceManager.GetString("Settings_General_InstallConfirm_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install failed.
        /// </summary>
        public static string Settings_General_InstallFailed_Title {
            get {
                return ResourceManager.GetString("Settings_General_InstallFailed_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This will copy the running exe to "{0}" and register it in Windows Settings &gt; Apps. Requires admin..
        /// </summary>
        public static string Settings_General_InstallSystemWideConfirm_Message_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstallSystemWideConfirm_Message_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install NetworkTrayAppDotNET system-wide?.
        /// </summary>
        public static string Settings_General_InstallSystemWideConfirm_Title {
            get {
                return ResourceManager.GetString("Settings_General_InstallSystemWideConfirm_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Settings_General_Install_Button {
            get {
                return ResourceManager.GetString("Settings_General_Install_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Settings_General_Installation_Header {
            get {
                return ResourceManager.GetString("Settings_General_Installation_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed (older build) at "{0}".{1}.
        /// </summary>
        public static string Settings_General_InstalledOlderBuild_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstalledOlderBuild_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed build {0}, running build {1}. Click Update to overwrite.{2}.
        /// </summary>
        public static string Settings_General_InstalledOutOfDate_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstalledOutOfDate_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed (build {0}) at "{1}"..
        /// </summary>
        public static string Settings_General_InstalledWithBuild_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstalledWithBuild_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed at "{0}"..
        /// </summary>
        public static string Settings_General_Installed_Format {
            get {
                return ResourceManager.GetString("Settings_General_Installed_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local user.
        /// </summary>
        public static string Settings_General_LocalUser_Title {
            get {
                return ResourceManager.GetString("Settings_General_LocalUser_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not installed. Will be placed at "{0}".{1}.
        /// </summary>
        public static string Settings_General_NotInstalled_Format {
            get {
                return ResourceManager.GetString("Settings_General_NotInstalled_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (requires admin).
        /// </summary>
        public static string Settings_General_RequiresAdmin_Suffix {
            get {
                return ResourceManager.GetString("Settings_General_RequiresAdmin_Suffix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch NetworkTrayAppDotNET when you sign in to Windows..
        /// </summary>
        public static string Settings_General_RunOnStartup_Description {
            get {
                return ResourceManager.GetString("Settings_General_RunOnStartup_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} Target: {1}.
        /// </summary>
        public static string Settings_General_RunOnStartup_OnDescriptionFormat {
            get {
                return ResourceManager.GetString("Settings_General_RunOnStartup_OnDescriptionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Autostart shortcut placed in shell:startup..
        /// </summary>
        public static string Settings_General_RunOnStartup_OnHeaderLine {
            get {
                return ResourceManager.GetString("Settings_General_RunOnStartup_OnHeaderLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run on startup automatically.
        /// </summary>
        public static string Settings_General_RunOnStartup_Title {
            get {
                return ResourceManager.GetString("Settings_General_RunOnStartup_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string Settings_General_Seconds_Suffix {
            get {
                return ResourceManager.GetString("Settings_General_Seconds_Suffix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_General_SectionHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not installed from the Microsoft Store..
        /// </summary>
        public static string Settings_General_StoreNotInstalled {
            get {
                return ResourceManager.GetString("Settings_General_StoreNotInstalled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Running from the Microsoft Store install..
        /// </summary>
        public static string Settings_General_StoreRunning {
            get {
                return ResourceManager.GetString("Settings_General_StoreRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System wide.
        /// </summary>
        public static string Settings_General_SystemWide_Title {
            get {
                return ResourceManager.GetString("Settings_General_SystemWide_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uninstall completed with warnings. Some files or registry entries may need manual removal. Check the install location and Windows Settings &gt; Apps..
        /// </summary>
        public static string Settings_General_UninstallIncomplete_Message {
            get {
                return ResourceManager.GetString("Settings_General_UninstallIncomplete_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uninstall incomplete.
        /// </summary>
        public static string Settings_General_UninstallIncomplete_Title {
            get {
                return ResourceManager.GetString("Settings_General_UninstallIncomplete_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Settings_General_Uninstall_Button {
            get {
                return ResourceManager.GetString("Settings_General_Uninstall_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Settings_General_Update_Button {
            get {
                return ResourceManager.GetString("Settings_General_Update_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Windows Store.
        /// </summary>
        public static string Settings_General_WindowsStore_Title {
            get {
                return ResourceManager.GetString("Settings_General_WindowsStore_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Settings_Hotkeys_Add_Button {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Add_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to delete this hotkey.
        /// </summary>
        public static string Settings_Hotkeys_DeleteHotkey_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_DeleteHotkey_ToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exists.
        /// </summary>
        public static string Settings_Hotkeys_Exists_Button {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Exists_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Settings_Hotkeys_Key_Enter {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_Enter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        public static string Settings_Hotkeys_Key_Escape {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_Escape", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PageDown.
        /// </summary>
        public static string Settings_Hotkeys_Key_PageDown {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_PageDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PageUp.
        /// </summary>
        public static string Settings_Hotkeys_Key_PageUp {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_PageUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string Settings_Hotkeys_Key_Space {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_Space", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_Alt {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_Alt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alt+Shift.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_AltShift {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_AltShift", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alt+Shift+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_AltShiftWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_AltShiftWin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alt+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_AltWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_AltWin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_Ctrl {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_Ctrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlAlt {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlAlt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Shift.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlAltShift {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlAltShift", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Shift+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlAltShiftWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlAltShiftWin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlAltWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlAltWin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlShift {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlShift", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlShiftWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlShiftWin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlWin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_Shift {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_Shift", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shift+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_ShiftWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_ShiftWin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_Win {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_Win", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open this settings window..
        /// </summary>
        public static string Settings_Hotkeys_OpenSettings_Description {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_OpenSettings_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string Settings_Hotkeys_OpenSettings_Title {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_OpenSettings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Settings_Hotkeys_Remove_Button {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Remove_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Settings_Hotkeys_SearchLabel {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_SearchLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bind a system-wide keyboard shortcut to each action. Bindings require at least one modifier key (Ctrl, Alt, Shift, or Win). All actions start unbound..
        /// </summary>
        public static string Settings_Hotkeys_SectionDescription {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_SectionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts.
        /// </summary>
        public static string Settings_Hotkeys_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_SectionHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hotkey service not available..
        /// </summary>
        public static string Settings_Hotkeys_Status_HotkeyServiceUnavailable {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Status_HotkeyServiceUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registered..
        /// </summary>
        public static string Settings_Hotkeys_Status_Registered {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Status_Registered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Theme_Appearance_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_Appearance_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark theme background color.
        /// </summary>
        public static string Settings_Theme_BackgroundColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundColor_DarkTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Override the default background color. Each variant falls back to the default when unset..
        /// </summary>
        public static string Settings_Theme_BackgroundColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundColor_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light theme background color.
        /// </summary>
        public static string Settings_Theme_BackgroundColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundColor_LightTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string Settings_Theme_BackgroundColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundColor_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Controls the overall size of the tray context menu. All elements scale from font size..
        /// </summary>
        public static string Settings_Theme_FontSize_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_FontSize_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string Settings_Theme_FontSize_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_FontSize_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to dark.
        /// </summary>
        public static string Settings_Theme_PickerTitle_DarkVariant {
            get {
                return ResourceManager.GetString("Settings_Theme_PickerTitle_DarkVariant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string Settings_Theme_PickerTitle_Format {
            get {
                return ResourceManager.GetString("Settings_Theme_PickerTitle_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to light.
        /// </summary>
        public static string Settings_Theme_PickerTitle_LightVariant {
            get {
                return ResourceManager.GetString("Settings_Theme_PickerTitle_LightVariant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Settings_Theme_Reset {
            get {
                return ResourceManager.GetString("Settings_Theme_Reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Applies rounded corners to the flyout, settings cards, buttons, and menus. Turn off for a squared-off look..
        /// </summary>
        public static string Settings_Theme_RoundedCorners_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_RoundedCorners_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rounded corners.
        /// </summary>
        public static string Settings_Theme_RoundedCorners_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_RoundedCorners_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_Theme_SectionHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark theme text color.
        /// </summary>
        public static string Settings_Theme_TextColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_TextColor_DarkTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Override the default text color. Each variant falls back to the default when unset..
        /// </summary>
        public static string Settings_Theme_TextColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_TextColor_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light theme text color.
        /// </summary>
        public static string Settings_Theme_TextColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_TextColor_LightTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        public static string Settings_Theme_TextColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_TextColor_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_ThemeStyle_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_Dark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Follow Windows, or force light / dark mode for this app..
        /// </summary>
        public static string Settings_Theme_ThemeStyle_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_ThemeStyle_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_Light", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Settings_Theme_ThemeStyle_System {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_System", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme style.
        /// </summary>
        public static string Settings_Theme_ThemeStyle_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Tray_Settings {
            get {
                return ResourceManager.GetString("Tray_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Uninstaller_Cancel {
            get {
                return ResourceManager.GetString("Uninstaller_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Uninstaller_Caption_Close {
            get {
                return ResourceManager.GetString("Uninstaller_Caption_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This will remove the installed copy of NetworkTrayAppDotNET and its registration in Windows Apps. Choose what to do with your settings..
        /// </summary>
        public static string Uninstaller_DefaultDescription {
            get {
                return ResourceManager.GetString("Uninstaller_DefaultDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Also remove %LOCALAPPDATA%\TrayAppDotNET\NetworkTrayAppDotNET, including settings.xml..
        /// </summary>
        public static string Uninstaller_DeleteSettings_DefaultDescription {
            get {
                return ResourceManager.GetString("Uninstaller_DeleteSettings_DefaultDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Also remove "{0}" including settings.xml..
        /// </summary>
        public static string Uninstaller_DeleteSettings_Description_Format {
            get {
                return ResourceManager.GetString("Uninstaller_DeleteSettings_Description_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete my settings.
        /// </summary>
        public static string Uninstaller_DeleteSettings_Title {
            get {
                return ResourceManager.GetString("Uninstaller_DeleteSettings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This will remove NetworkTrayAppDotNET installed at "{0}" and its entry in Windows Settings &gt; Apps. Choose what to do with your settings..
        /// </summary>
        public static string Uninstaller_Description_Format {
            get {
                return ResourceManager.GetString("Uninstaller_Description_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Leave settings.xml in place so a future install picks them up..
        /// </summary>
        public static string Uninstaller_KeepSettings_Description {
            get {
                return ResourceManager.GetString("Uninstaller_KeepSettings_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keep my settings.
        /// </summary>
        public static string Uninstaller_KeepSettings_Title {
            get {
                return ResourceManager.GetString("Uninstaller_KeepSettings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uninstall NetworkTrayAppDotNET.
        /// </summary>
        public static string Uninstaller_SectionHeader {
            get {
                return ResourceManager.GetString("Uninstaller_SectionHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uninstall NetworkTrayAppDotNET.
        /// </summary>
        public static string Uninstaller_Title {
            get {
                return ResourceManager.GetString("Uninstaller_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstaller_UninstallButton {
            get {
                return ResourceManager.GetString("Uninstaller_UninstallButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        public static string Uninstaller_UninstallingButton {
            get {
                return ResourceManager.GetString("Uninstaller_UninstallingButton", resourceCulture);
            }
        }
    }
}
