name: Battery Build

on:
  push:
    branches: [main, master]
    paths:
      - BatteryTrayAppDotNET/**
      - TrayAppDotNETCommon/**
      - Directory.Build.props
      - TrayAppDotNET.Parent.props
      - TrayAppDotNET.Parent.targets
      - .github/workflows/battery-build.yml
      - .github/workflows/_trayapp-build.yml
  pull_request:
    paths:
      - BatteryTrayAppDotNET/**
      - TrayAppDotNETCommon/**
      - Directory.Build.props
      - TrayAppDotNET.Parent.props
      - TrayAppDotNET.Parent.targets
      - .github/workflows/battery-build.yml
      - .github/workflows/_trayapp-build.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_trayapp-build.yml
    with:
      app_name: BatteryTrayAppDotNET
      project_path: BatteryTrayAppDotNET/src/BatteryTrayAppDotNET.csproj
      artifact_slug: battery-tray-app
