name: Battery Native AOT

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  native-aot:
    uses: ./.github/workflows/_trayapp-native-aot.yml
    with:
      app_name: BatteryTrayAppDotNET
      project_path: BatteryTrayAppDotNET/src/BatteryTrayAppDotNET.csproj
      artifact_slug: battery-tray-app
